name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is named differently

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build and Deploy
        working-directory: frontend
        env:
          CI: false
        run: npm run deploy
