name: Deploy to GitHub Pages

on:
  push:
    branches:
      - rust  # Deploy only when pushing to "rust" branch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Rust (for backend)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install wasm-pack (for WebAssembly)
        run: cargo install wasm-pack

      - name: Build Backend (WASM)
        run: |
          cd backend
          wasm-pack build --target web --out-dir pkg --out-name index

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/dist
