name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change to "main" if your default branch is "main"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          echo "$PWD/upstream/emscripten" >> $GITHUB_PATH
          emcc --version

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # Configure Git identity for gh-pages commit
      - name: Configure Git Identity
        working-directory: frontend
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Build and Deploy
        working-directory: frontend
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
